server:
  tomcat:
    max-connections: 20
    threads.max: 5

spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: false
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
