server:
  port: 8080

spring:
  application:
    name: world-cup

  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # none create, create-drop, validate, update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true
    open-in-view: false

  output:
    ansi:
      enabled: always

  flyway:
    enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: top.ten.ranker@gmail.com
    password: ${EMAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp.auth: true
        smtp.starttls.enable: true
        smtp.timeout: 5000
        smtp.writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
    health:
      show-details: always

logging:
  level:
    root: info
    org.springframework: info
    com.ab.worldcup: debug


worldcup:
  start-date-time-config: '2022-11-20 19:00:00+00'
  admin-emails: "yoav200@gmail.com,yoav.alhalel@bnymellon.com"
  confirmation-timeout-minutes: 60
  app-url: "http://localhost:8080"
  allowed-domains: "gmail.com,bnymellon.com"
