server:
  port: 8080

app:
  socialauth:
    base-callback-url: "http://localhost:8080/socialauth/"
    success-page-url: "/#/welcome"
    access-denied-page-url: "/#/access-denied"

spring:
  application:
    name: world-cup
  datasource:
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
     hibernate:
       order_updates: true
       order_inserts: true
       jdbc:
         batch_size: 200
         batch_versioned_data: true
  h2:
    console:
      enabled: true
      path: /h2

  output:
    ansi:
      enabled: always

# Set the file size limit (default 1Mb). If you want to specify that files be
# unlimited set the multipart.maxFileSize property to -1.
multipart:
  maxFileSize: 3Mb
