spring:
  datasource:
      driver-class-name:
      url:
      username:
      password:
      test-on-borrow: true
      test-on-connect: true
      validation-query:

    jpa:
      database-platform:
      hibernate:
        ddl-auto: none

    h2:
      console:
        enabled: false