server:
  port: 8080

spring:
  application:
    name: world-cup
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 200
          batch_versioned_data: true
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2

  output:
    ansi:
      enabled: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: top.ten.ranker@gmail.com
    password: ${EMAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp.auth: true
        smtp.starttls.enable: true
        smtp.timeout: 5000
        smtp.writetimeout: 5000


management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
    health:
      show-details: always

logging:
  level:
    root: info
    org.springframework: info
    com.ab.worldcup: debug


worldcup:
  start-date-time: '2022-11-20 19:00:00+00'
  admin-emails: "yoav200@gmail.com,yoav.alhalel@bnymellon.com"

