server:
  port: 8080

spring:
  application:
    name: world-cup
  datasource:
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: 200
          batch_versioned_data: true
  h2:
    console:
      enabled: true
      path: /h2

  output:
    ansi:
      enabled: always

worldcup:
  socialauth:
    base-callback-url: "http://localhost:8080"
    success-page-url: "#/welcome"
    access-denied-page-url: "#/access-denied"