GroupA=
GroupB=
GroupC=
GroupD=
GroupE=
GroupF=
GroupG=
GroupH=
GroupI=
GroupJ=
GroupK=
GroupL=

# in case of a complete tie in a group, the tied teams will appear according to the order fifa decided.
# for example, in case of a tie in group D between USA and TURKEY, here USA will get advantage