GroupA=MEXICO,SOUTH KOREA,CZECH REPUBLIC,SOUTH AFRICA
GroupB=SWITZERLAND,CANADA,QATAR,BOSNIA AND HERZEGOVINA
GroupC=BRAZIL,MOROCCO,SCOTLAND,HAITI
GroupD=UNITED STATES,AUSTRALIA,PARAGUAY,TURKEY
GroupE=GERMANY,ECUADOR,IVORY COAST,CURACAO
GroupF=NETHERLANDS,JAPAN,TUNISIA,SWEDEN
GroupG=BELGIUM,IRAN,EGYPT,NEW ZEALAND
GroupH=SPAIN,URUGUAY,SAUDI ARABIA,CAPE VERDE
GroupI=FRANCE,SENEGAL,NORWAY,IRAQ
GroupJ=ARGENTINA,AUSTRIA,ALGERIA,JORDAN
GroupK=PORTUGAL,COLOMBIA,UZBEKISTAN,DR CONGO
GroupL=ENGLAND,CROATIA,PANAMA,GHANA
