--
-- H2-compatible schema (adapted from PostgreSQL V1)
--

CREATE TABLE account
(
    id             bigint      NOT NULL,
    createdat      timestamp,
    email          varchar(45) NOT NULL,
    enabled        boolean,
    first_name     varchar(20) NOT NULL,
    last_name      varchar(20) NOT NULL,
    locked         boolean,
--     password varchar(64) NOT NULL,
    status         varchar(255),
    updatedatetime timestamp,
    PRIMARY KEY (id),
    CONSTRAINT uk_account_email UNIQUE (email)
);

CREATE TABLE bet
(
    id          bigint NOT NULL,
    description varchar(255),
    locktime    timestamp,
    matchid     bigint,
    stageid     varchar(255),
    type        varchar(255),
    PRIMARY KEY (id)
);

CREATE TABLE match
(
    matchid bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    kickoff timestamp,
    status  integer,
    PRIMARY KEY (matchid)
);

CREATE TABLE group_match
(
    groupid  varchar(255),
    matchid  bigint NOT NULL,
    awayteam bigint,
    hometeam bigint,
    PRIMARY KEY (matchid)
);

CREATE TABLE knockout_match
(
    awayteamcode varchar(255),
    hometeamcode varchar(255),
    matchcode    varchar(255),
    stageid      varchar(255),
    matchid      bigint NOT NULL,
    PRIMARY KEY (matchid)
);

CREATE TABLE knockout_team
(
    matchid  bigint NOT NULL,
    awayteam bigint,
    hometeam bigint,
    PRIMARY KEY (matchid)
);

CREATE TABLE match_result
(
    matchid        bigint NOT NULL,
    awayteamgoals  integer,
    hometeamgoals  integer,
    matchqualifier integer,
    awayteam       bigint,
    hometeam       bigint,
    PRIMARY KEY (matchid)
);

CREATE TABLE qualifier
(
    knockoutteamcode varchar(255) NOT NULL,
    stageid          varchar(255),
    teamid           bigint,
    PRIMARY KEY (knockoutteamcode)
);

CREATE TABLE ranking
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date      timestamp,
    points    integer,
    accountid bigint,
    PRIMARY KEY (id)
);

CREATE TABLE team
(
    id            bigint NOT NULL,
    appearances   integer,
    code          varchar(255),
    iso_code      varchar(10),
    confederation varchar(255),
    fifaranking   integer,
    groupid       varchar(255),
    name          varchar(255),
    titles        integer,
    PRIMARY KEY (id)
);

CREATE TABLE user_bet
(
    awayteamgoals    integer,
    hometeamgoals    integer,
    knockoutteamcode integer,
    accountid        bigint NOT NULL,
    betid            bigint NOT NULL,
    awayteam         bigint,
    hometeam         bigint,
    qualifier        bigint,
    PRIMARY KEY (accountid, betid)
);

-- Virtual coins: stores coin events that contribute to the shared prize pool
CREATE TABLE coin_event
(
    id             bigint      NOT NULL,
    event_type     varchar(50) NOT NULL,
    coins          integer     NOT NULL,
    account_id     bigint,
    reference_id   bigint,
    created_at     timestamp   DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- Leagues (group ranking)
CREATE TABLE league
(
    id          bigint    NOT NULL,
    name        varchar(100) NOT NULL,
    created_by  bigint    NOT NULL,
    created_at  timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE league_membership
(
    id          bigint    NOT NULL,
    league_id   bigint    NOT NULL,
    email       varchar(45) NOT NULL,
    account_id  bigint,
    joined_at   timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_league_membership UNIQUE (league_id, email)
);

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1000 INCREMENT BY 1;

-- Foreign keys
ALTER TABLE group_match
    ADD CONSTRAINT fk_groupmatch_match FOREIGN KEY (matchid) REFERENCES match (matchid);
ALTER TABLE group_match
    ADD CONSTRAINT fk_groupmatch_hometeam FOREIGN KEY (hometeam) REFERENCES team (id);
ALTER TABLE group_match
    ADD CONSTRAINT fk_groupmatch_awayteam FOREIGN KEY (awayteam) REFERENCES team (id);
ALTER TABLE knockout_match
    ADD CONSTRAINT fk_knockoutmatch_match FOREIGN KEY (matchid) REFERENCES match (matchid);
ALTER TABLE knockout_team
    ADD CONSTRAINT fk_knockoutteam_hometeam FOREIGN KEY (hometeam) REFERENCES team (id);
ALTER TABLE knockout_team
    ADD CONSTRAINT fk_knockoutteam_awayteam FOREIGN KEY (awayteam) REFERENCES team (id);
ALTER TABLE match_result
    ADD CONSTRAINT fk_matchresult_hometeam FOREIGN KEY (hometeam) REFERENCES team (id);
ALTER TABLE match_result
    ADD CONSTRAINT fk_matchresult_awayteam FOREIGN KEY (awayteam) REFERENCES team (id);
ALTER TABLE qualifier
    ADD CONSTRAINT fk_qualifier_team FOREIGN KEY (teamid) REFERENCES team (id);
ALTER TABLE ranking
    ADD CONSTRAINT fk_ranking_account FOREIGN KEY (accountid) REFERENCES account (id);
ALTER TABLE user_bet
    ADD CONSTRAINT fk_userbet_account FOREIGN KEY (accountid) REFERENCES account (id);
ALTER TABLE user_bet
    ADD CONSTRAINT fk_userbet_bet FOREIGN KEY (betid) REFERENCES bet (id);
ALTER TABLE user_bet
    ADD CONSTRAINT fk_userbet_hometeam FOREIGN KEY (hometeam) REFERENCES team (id);
ALTER TABLE user_bet
    ADD CONSTRAINT fk_userbet_awayteam FOREIGN KEY (awayteam) REFERENCES team (id);
ALTER TABLE user_bet
    ADD CONSTRAINT fk_userbet_qualifier FOREIGN KEY (qualifier) REFERENCES team (id);
ALTER TABLE coin_event
    ADD CONSTRAINT fk_coin_event_account FOREIGN KEY (account_id) REFERENCES account (id);
ALTER TABLE league
    ADD CONSTRAINT fk_league_creator FOREIGN KEY (created_by) REFERENCES account (id);
ALTER TABLE league_membership
    ADD CONSTRAINT fk_league_membership_league FOREIGN KEY (league_id) REFERENCES league (id);
ALTER TABLE league_membership
    ADD CONSTRAINT fk_league_membership_account FOREIGN KEY (account_id) REFERENCES account (id);