drop table if exists account CASCADE 
drop table if exists bet CASCADE 
drop table if exists ConfirmationToken CASCADE 
drop table if exists group_match CASCADE 
drop table if exists knockout_match CASCADE 
drop table if exists knockout_team CASCADE 
drop table if exists match CASCADE 
drop table if exists match_result CASCADE 
drop table if exists qualifier CASCADE 
drop table if exists ranking CASCADE 
drop table if exists team CASCADE 
drop table if exists user_bet CASCADE 
drop sequence if exists hibernate_sequence
create sequence hibernate_sequence start with 1 increment by 1
create table account (id bigint not null, createdAt timestamp, email varchar(45) not null, enabled boolean, first_name varchar(20) not null, last_name varchar(20) not null, locked boolean, password varchar(64) not null, status varchar(255), updateDateTime timestamp, primary key (id))
create table bet (id bigint not null, description varchar(255), lockTime timestamp, matchId bigint, stageId varchar(255), type varchar(255), primary key (id))
create table ConfirmationToken (id bigint not null, confirmedAt timestamp, createdAt timestamp, expiresAt timestamp not null, token varchar(255) not null, updateDateTime timestamp, usages integer not null, account_id bigint not null, primary key (id))
create table group_match (groupId varchar(255), matchId bigint not null, awayTeam bigint, homeTeam bigint, primary key (matchId))
create table knockout_match (awayTeamCode varchar(255), homeTeamCode varchar(255), matchCode varchar(255), stageId varchar(255), matchId bigint not null, primary key (matchId))
create table knockout_team (matchId bigint not null, awayTeam bigint, homeTeam bigint, primary key (matchId))
create table match (matchId bigint generated by default as identity, kickoff timestamp, status integer, primary key (matchId))
create table match_result (matchId bigint not null, awayTeamGoals integer, homeTeamGoals integer, matchQualifier integer, awayTeam bigint, homeTeam bigint, primary key (matchId))
create table qualifier (knockoutTeamCode varchar(255) not null, stageId varchar(255), teamId bigint, primary key (knockoutTeamCode))
create table ranking (id bigint generated by default as identity, date timestamp, points integer, accountId bigint, primary key (id))
create table team (id bigint not null, appearances integer, code varchar(255), confederation varchar(255), fifaRanking integer, groupId varchar(255), name varchar(255), titles integer, primary key (id))
create table user_bet (awayTeamGoals integer, homeTeamGoals integer, knockoutTeamCode integer, accountId bigint not null, betId bigint not null, awayTeam bigint, homeTeam bigint, qualifier bigint, primary key (accountId, betId))
alter table account add constraint UK_q0uja26qgu1atulenwup9rxyr unique (email)
alter table ConfirmationToken add constraint UK_5yeek6arig5t6anh1oo2s5sar unique (token)
alter table ConfirmationToken add constraint FKp8s3u5mts4v2ohshjshifm29v foreign key (account_id) references account
alter table group_match add constraint FKnmhppe72nbkrqlha9tmsvfmq1 foreign key (awayTeam) references team
alter table group_match add constraint FKgn9rhtdt2qq2tmnft32wi1tms foreign key (homeTeam) references team
alter table group_match add constraint FK7gb0gnocoyfphvsnvy9h8e8c foreign key (matchId) references match
alter table knockout_match add constraint FK2eke8kdffthylcl4kegigx6xs foreign key (matchId) references match
alter table knockout_team add constraint FK5nbjpb11du7q7434sldmrjeoy foreign key (awayTeam) references team
alter table knockout_team add constraint FKb16c9podhm48u07yhrv0y1f8w foreign key (homeTeam) references team
alter table match_result add constraint FKkp7p9tgpthbbkq1qli88d49qk foreign key (awayTeam) references team
alter table match_result add constraint FKj744my4jm4bgb9oixruj2nwj1 foreign key (homeTeam) references team
alter table qualifier add constraint FKh86wg757nympdrhkpcb81bfn0 foreign key (teamId) references team
alter table ranking add constraint FK6qv7r3hti60dasjj793iki7fe foreign key (accountId) references account
alter table user_bet add constraint FK4b8yu2ukr1o5ppteascwio75j foreign key (accountId) references account
alter table user_bet add constraint FKj2oy612nryr9l2tqsu0a85eh3 foreign key (betId) references bet
alter table user_bet add constraint FKl4edlaqbn3x4gt4tpm5kix7t7 foreign key (awayTeam) references team
alter table user_bet add constraint FK7huvf4ughpqdylrx07d8e549o foreign key (homeTeam) references team
alter table user_bet add constraint FKh05slrqce9psiu1a78uakk0f6 foreign key (qualifier) references team